project_id = "qnuyiztwqbzcbuheznnv"

[functions.payscrow-release]
verify_jwt = false

[functions.cron-dispute-check]
verify_jwt = false

[functions.payscrow-webhook]
verify_jwt = false

[functions.paystack-webhook]
verify_jwt = false

[functions.check-email]
verify_jwt = false

[functions.reset-pin]
verify_jwt = false
